version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile

  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: WebApp/Dockerfile

  angular-app:
    image: ${DOCKER_REGISTRY-}angular-app
    build:
      context: ../angular
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "4200:4200"
